# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - test_group_controller
  # action_ns: /test_group_controller/follow_joint_trajectory

  test_group_controller:
    type: FollowJointTrajectory
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    action_ns: follow_joint_trajectory