controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    exchanger_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

exchanger_group_controller:
  ros__parameters:
    joints:
      - joint2
      - joint3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity